### PR TITLE
Translated String values into Polish

### PR DESCRIPTION
**Pull request by KyleHodgetts**
I translated all String values into their Polish equivalents.

### CODE REVIEW

**Comment by libreliodev** [comment]
@KyleHodgetts Many thanks for this translation. Can you please confirm that you agree to give the IP rights on this work to Librelio for this project?

@intrications Can we merge this pull request?

**Comment by intrications** [comment]
@libreliodev Yes, this can be merged automatically once we get confirmation from @KyleHodgetts about the IP rights.

**Comment by KyleHodgetts** [comment]
Sorry, I've only just been notified. Yes of course you can.

**Comment by KyleHodgetts** [comment]
@libreliodev @intrications

**Comment by libreliodev** [comment]
It's done.
Thanks @KyleHodgetts.

**Pull request merged**
